"""noticias assignment lock fields (asignado_a, asignado_at, motivo_rechazo)

Revision ID: 1c9fad29b98d
Revises: f142223dde8b
Create Date: 2026-07-19 17:09:27.910779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1c9fad29b98d'
down_revision: Union[str, None] = 'f142223dde8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('asignado_a', sa.UUID(), nullable=True))
    op.add_column('noticias', sa.Column('asignado_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('noticias', sa.Column('motivo_rechazo', sa.Text(), nullable=True))
    op.create_index(op.f('ix_noticias_asignado_a'), 'noticias', ['asignado_a'], unique=False)
    op.create_foreign_key(None, 'noticias', 'usuarios', ['asignado_a'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_index(op.f('ix_noticias_asignado_a'), table_name='noticias')
    op.drop_column('noticias', 'motivo_rechazo')
    op.drop_column('noticias', 'asignado_at')
    op.drop_column('noticias', 'asignado_a')
    # ### end Alembic commands ###
