"""pipeline_runs table and noticias.pipeline_run_id

Revision ID: f142223dde8b
Revises: 0002
Create Date: 2026-07-19 16:54:53.865645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f142223dde8b'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('grabacion_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'en_progreso', 'completado', 'error', name='estado_pipeline_run'), nullable=False),
    sa.Column('iniciado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('noticias_generadas', sa.Integer(), nullable=False),
    sa.Column('error_mensaje', sa.Text(), nullable=True),
    sa.Column('metadatos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grabacion_id'], ['grabaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_grabacion_id'), 'pipeline_runs', ['grabacion_id'], unique=False)
    op.create_index(op.f('ix_auditoria_registro_id'), 'auditoria', ['registro_id'], unique=False)
    op.create_index(op.f('ix_auditoria_tabla'), 'auditoria', ['tabla'], unique=False)
    op.create_index(op.f('ix_cliente_noticias_noticia_id'), 'cliente_noticias', ['noticia_id'], unique=False)
    op.create_index(op.f('ix_cliente_noticias_tenant_id'), 'cliente_noticias', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_etiquetados_privados_cliente_noticia_id'), 'etiquetados_privados', ['cliente_noticia_id'], unique=False)
    op.create_index(op.f('ix_etiquetados_privados_tenant_id'), 'etiquetados_privados', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_grabaciones_programa_id'), 'grabaciones', ['programa_id'], unique=False)
    op.create_index(op.f('ix_informes_semanales_tenant_id'), 'informes_semanales', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_login_events_usuario_id'), 'login_events', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_monitoring_profiles_tenant_id'), 'monitoring_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_noticia_versiones_noticia_id'), 'noticia_versiones', ['noticia_id'], unique=False)
    op.add_column('noticias', sa.Column('pipeline_run_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_noticias_grabacion_id'), 'noticias', ['grabacion_id'], unique=False)
    op.create_index(op.f('ix_noticias_pipeline_run_id'), 'noticias', ['pipeline_run_id'], unique=False)
    op.create_foreign_key(None, 'noticias', 'pipeline_runs', ['pipeline_run_id'], ['id'])
    op.create_index(op.f('ix_programas_medio_id'), 'programas', ['medio_id'], unique=False)
    op.create_index(op.f('ix_subtemas_tema_id'), 'subtemas', ['tema_id'], unique=False)
    op.create_index(op.f('ix_transcripciones_grabacion_id'), 'transcripciones', ['grabacion_id'], unique=True)
    op.create_index(op.f('ix_usuarios_tenant_id'), 'usuarios', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_tenant_id'), table_name='usuarios')
    op.drop_index(op.f('ix_transcripciones_grabacion_id'), table_name='transcripciones')
    op.drop_index(op.f('ix_subtemas_tema_id'), table_name='subtemas')
    op.drop_index(op.f('ix_programas_medio_id'), table_name='programas')
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_index(op.f('ix_noticias_pipeline_run_id'), table_name='noticias')
    op.drop_index(op.f('ix_noticias_grabacion_id'), table_name='noticias')
    op.drop_column('noticias', 'pipeline_run_id')
    op.drop_index(op.f('ix_noticia_versiones_noticia_id'), table_name='noticia_versiones')
    op.drop_index(op.f('ix_monitoring_profiles_tenant_id'), table_name='monitoring_profiles')
    op.drop_index(op.f('ix_login_events_usuario_id'), table_name='login_events')
    op.drop_index(op.f('ix_informes_semanales_tenant_id'), table_name='informes_semanales')
    op.drop_index(op.f('ix_grabaciones_programa_id'), table_name='grabaciones')
    op.drop_index(op.f('ix_etiquetados_privados_tenant_id'), table_name='etiquetados_privados')
    op.drop_index(op.f('ix_etiquetados_privados_cliente_noticia_id'), table_name='etiquetados_privados')
    op.drop_index(op.f('ix_cliente_noticias_tenant_id'), table_name='cliente_noticias')
    op.drop_index(op.f('ix_cliente_noticias_noticia_id'), table_name='cliente_noticias')
    op.drop_index(op.f('ix_auditoria_tabla'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_registro_id'), table_name='auditoria')
    op.drop_index(op.f('ix_pipeline_runs_grabacion_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
